name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Get the current version of Go from project.
        run: $Env:GO_VERSION_FROM_PROJECT=type go.mod | select -first 3 | select -last 1 | %{ $_ -split ' ' } | select -last 1
      - name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
        id: go
      - name: Get dependencies
        run: go get .
      - name: Build Test
        run: go build .
